const PERMISSIONS = {
  SERVICES_READ: 'SERVICES_READ',
  SERVICES_WRITE: 'SERVICES_WRITE',
  PROJECTS_READ: 'PROJECTS_READ',
  PROJECTS_WRITE: 'PROJECTS_WRITE',
  HOMEPAGE_READ: 'HOMEPAGE_READ',
  HOMEPAGE_WRITE: 'HOMEPAGE_WRITE',
  SETTINGS_READ: 'SETTINGS_READ',
  SETTINGS_WRITE: 'SETTINGS_WRITE',
  CONTENT_READ: 'CONTENT_READ',
  CONTENT_WRITE: 'CONTENT_WRITE',
  JOBS_READ: 'JOBS_READ',
  JOBS_WRITE: 'JOBS_WRITE',
  COMMUNITY_READ: 'COMMUNITY_READ',
  COMMUNITY_WRITE: 'COMMUNITY_WRITE',
  LEADS_READ: 'LEADS_READ',
  LEADS_WRITE: 'LEADS_WRITE',
  MEDIA_UPLOAD: 'MEDIA_UPLOAD',
  USERS_MANAGE: 'USERS_MANAGE',
  ROLES_MANAGE: 'ROLES_MANAGE',
  SECURITY_LOGS_READ: 'SECURITY_LOGS_READ',
};

const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  CONTENT_MANAGER: [
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.SERVICES_WRITE,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_WRITE,
    PERMISSIONS.HOMEPAGE_READ,
    PERMISSIONS.HOMEPAGE_WRITE,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_WRITE,
    PERMISSIONS.COMMUNITY_READ,
    PERMISSIONS.COMMUNITY_WRITE,
    PERMISSIONS.MEDIA_UPLOAD,
  ],
  HR_MANAGER: [
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.JOBS_WRITE,
    PERMISSIONS.LEADS_READ,
  ],
  MARKETING_MANAGER: [
    PERMISSIONS.LEADS_READ,
    PERMISSIONS.LEADS_WRITE,
    PERMISSIONS.SERVICES_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.COMMUNITY_READ,
  ],
};

module.exports = { PERMISSIONS, ROLE_PERMISSIONS };
